//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverBill
    {
        public int DriverBillId { get; set; }
        public int DriverId { get; set; }
        public Nullable<int> MonthlyMembership { get; set; }
        public Nullable<int> SupportExpense { get; set; }
        public Nullable<int> CallExpense { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public bool Paid { get; set; }
        public bool SMSSent { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> AmountToPay { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> CallsCount { get; set; }
    
        public virtual Driver Driver { get; set; }
    }
}
