//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MahanGashtEntities : DbContext
    {
        public MahanGashtEntities()
            : base("name=MahanGashtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agency> Agencies { get; set; }
        public virtual DbSet<AgencyBill> AgencyBills { get; set; }
        public virtual DbSet<Call> Calls { get; set; }
        public virtual DbSet<CallType> CallTypes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DriverBill> DriverBills { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<ServiceType> ServiceTypes { get; set; }
        public virtual DbSet<SM> SMS { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VAgency> VAgencies { get; set; }
        public virtual DbSet<VCall> VCalls { get; set; }
        public virtual DbSet<VCustomer> VCustomers { get; set; }
        public virtual DbSet<VDriver> VDrivers { get; set; }
    }
}
