//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceType
    {
        public int ServiceTypeId { get; set; }
        public string Type { get; set; }
        public string Items { get; set; }
        public int OwnerType { get; set; }
        public Nullable<int> M1 { get; set; }
        public Nullable<int> M2 { get; set; }
        public Nullable<int> M3 { get; set; }
        public Nullable<int> A1 { get; set; }
    }
}
