//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM
    {
        public int ID { get; set; }
        public string Content { get; set; }
        public string FromNumber { get; set; }
        public string ToNumber { get; set; }
        public System.DateTime Created { get; set; }
        public string PCreated { get; set; }
        public string Category { get; set; }
        public string Status { get; set; }
    }
}
