//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCall
    {
        public int CallId { get; set; }
        public int Code { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public int Duration { get; set; }
        public string CallerId { get; set; }
        public string AgencyName { get; set; }
        public string DriverName { get; set; }
        public int CallTypeId { get; set; }
        public string CalledId { get; set; }
        public string Type { get; set; }
        public string ServiceType { get; set; }
        public int ServiceTypeId { get; set; }
        public string CIdPart { get; set; }
    }
}
